# Generated by Django 5.2.4 on 2025-07-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
