# Generated by Django 5.2.4 on 2025-07-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_slug_post_uid_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='department',
            new_name='Post',
        ),
    ]
